
---
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-airbyte-yml
  namespace: airbyte
  labels:
    app.kubernetes.io/name: airbyte
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.53.1"
type: Opaque
data:
  fileContents: "CiAgICA="
---
# Source: airbyte/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airbyte-airbyte-secrets
  namespace: airbyte
  labels:
    app.kubernetes.io/name: airbyte
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.53.1"
type: Opaque
stringData:
  # todo edit for external database
  DATABASE_PASSWORD: "airbyte"
  DATABASE_USER: airbyte
  WORKLOAD_API_BEARER_TOKEN: ".Values.workload-api.bearerToken"
  DEFAULT_MINIO_ACCESS_KEY: minio
  DEFAULT_MINIO_SECRET_KEY: minio123


