---
# Source: airbyte/charts/cron/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-cron
  namespace: airbyte
  labels:
    app.kubernetes.io/name: cron
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.53.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cron
      app.kubernetes.io/instance: airbyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cron
        app.kubernetes.io/instance: airbyte
    spec:
      serviceAccountName: airbyte-admin
      automountServiceAccountToken: true
      containers:
        - name: airbyte-cron
          image: airbyte/cron:0.53.1
          imagePullPolicy: "IfNotPresent"
          env:
          - name: AIRBYTE_VERSION
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: AIRBYTE_VERSION
          - name: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: airbyte-airbyte-secrets
                key: DATABASE_PASSWORD
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: DATABASE_URL
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: airbyte-airbyte-secrets
                key: DATABASE_USER
          - name: MICROMETER_METRICS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: MICROMETER_METRICS_ENABLED
          - name: MICROMETER_METRICS_STATSD_FLAVOR
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: MICROMETER_METRICS_STATSD_FLAVOR
          - name: MICRONAUT_ENVIRONMENTS
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: CRON_MICRONAUT_ENVIRONMENTS
          - name: TEMPORAL_HOST
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: TEMPORAL_HOST
          - name: SEGMENT_WRITE_KEY
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: SEGMENT_WRITE_KEY
          - name: STATSD_HOST
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: STATSD_HOST
          - name: STATSD_PORT
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: STATSD_PORT
          - name: TRACKING_STRATEGY
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: TRACKING_STRATEGY
          - name: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
          - name: WORKLOAD_API_BEARER_TOKEN
            valueFrom:
              secretKeyRef:
                name: airbyte-airbyte-secrets
                key: WORKLOAD_API_BEARER_TOKEN
          - name: WORKLOAD_API_HOST
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: WORKLOAD_API_HOST
          - name: WORKSPACE_DOCKER_MOUNT
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: WORKSPACE_DOCKER_MOUNT
          - name: WORKSPACE_ROOT
            valueFrom:
              configMapKeyRef:
                name: airbyte-airbyte-env
                key: WORKSPACE_ROOT

          # Values from secret

          # Values from env

          # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
          resources:
            limits: {}
            requests: {}