---
# Source: airbyte/charts/webapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-webapp
  namespace: airbyte
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.53.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/instance: airbyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/instance: airbyte
    spec:
      serviceAccountName: airbyte-admin
      containers:
      - name: airbyte-webapp-container
        image: airbyte/webapp:0.53.1
        imagePullPolicy: "IfNotPresent"
        env:
        - name: TRACKING_STRATEGY
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: TRACKING_STRATEGY
        - name: INTERNAL_API_HOST
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: INTERNAL_API_HOST
        - name: KEYCLOAK_INTERNAL_HOST
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: KEYCLOAK_INTERNAL_HOST
        - name: AIRBYTE_VERSION
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: AIRBYTE_VERSION
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: airbyte-airbyte-env
              key: API_URL
        # Values from secret

        # Values from env

        # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits: {}
          requests: {}
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/templates/
      volumes:
      - name: config
        configMap:
          name: airbyte-webapp-nginx
          items:
          - key: default.conf.template
            path: default.conf.template
---
# Source: airbyte/charts/webapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airbyte-airbyte-webapp-svc
  namespace: airbyte
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/version: "0.53.1"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: airbyte
---
# for this bug
# https://github.com/airbytehq/airbyte/issues/25174
apiVersion: v1
kind: ConfigMap
metadata:
  name: airbyte-webapp-nginx
  namespace: airbyte
data:
  default.conf.template: |
    upstream api-server {
        server $INTERNAL_API_HOST;
    }

    upstream keycloak {
        server $KEYCLOAK_INTERNAL_HOST;
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        add_header Content-Security-Policy "script-src * 'unsafe-inline'; worker-src 'self' blob:;";

        location / {
            root   /usr/share/nginx/html;

            location ~ ^/docs/.* {
                try_files $uri $uri/ =404;
            }

            location ~ ^/(?!(assets/.*)) {
                try_files $uri $uri/ /index.html;
            }
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /api/ {
            fastcgi_read_timeout 1h;
            proxy_read_timeout 1h;
            client_max_body_size 200M;
            proxy_pass http://api-server/api/;

            # Unset X-Airbyte-Auth header so that it cannot be used by external requests for authentication
            proxy_set_header X-Airbyte-Auth "";
        }

        location /auth/ {
            # Block access to anything not under /auth/realms or /auth/resources
            location ~ "/auth/(?!(realms|resources).*)" {
                return 404;
            }
            proxy_set_header    Host               $host;
            proxy_set_header    X-Real-IP          $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Host   $host;
            proxy_set_header    X-Forwarded-Server $host;
            proxy_set_header    X-Forwarded-Proto  $scheme;
            proxy_hide_header   Content-Security-Policy;
            proxy_pass http://keycloak/auth/;
        }
    }